name: CGL & unit tests

on:
    push:
        branches:
            - '**'
            - '!l10n_*'
    pull_request:
        branches:
            - '**'
            - '!l10n_*'

jobs:
    unit-tests:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [7.1]
        steps:
            -   uses: actions/checkout@v2
            -   run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
            # composer
            -   run: composer update --no-progress --no-suggest
            # Run tests
            -   run: composer tests-for:ci

