name: CGL & unit tests

on:
    push:
        branches:
            - '**'
            - '!l10n_*'
    pull_request:
        branches:
            - '**'
            - '!l10n_*'

jobs:
    unit-tests:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [7.2, 7.3, 7.4]
        steps:
            -   uses: actions/checkout@v2
            # PHP 7.1-.4 are available in ubuntu-18.04
            # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts
            -   run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
            # composer
            -   run: composer update --no-interaction --no-progress
            # Run tests
            -   run: composer test:cgl
            -   run: composer test:unit
            # Push to coveralls
            -   run: |
                    COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} \
                        .build/bin/php-coveralls \
                        --root_dir=. --env=prod --verbose
                if: github.ref == 'refs/heads/master'
    unit-tests-lowest:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [7.2, 7.3]
        steps:
            -   uses: actions/checkout@v2
            # PHP 7.1, 7.2 and 7.3 are available in ubuntu-18.04
            # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts
            -   run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
            # composer
            -   run: composer update --prefer-lowest --no-progress --no-suggest
            # Run tests
            -   run: composer test:unit
